name: CI

on:
  push:
    branches-ignore:
      # avoid loop when changesets creates PR branches
      - 'changeset-release/**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # avoid cache poisoning
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # avoid cache poisoning
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Prettier
        run: npm run prettier

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # avoid cache poisoning
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # avoid cache poisoning
      - name: Install dependencies
        run: npm ci
      - name: Run integration tests
        run: npm run test:integration
